# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from lidar_perception/PerceptionObject.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class PerceptionObject(genpy.Message):
  _md5sum = "152b93ea38a71a29b81420f7d89d356c"
  _type = "lidar_perception/PerceptionObject"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 id
geometry_msgs/Vector3 position
geometry_msgs/Vector3 velocity
float64 heading
geometry_msgs/Vector3 bounding_box
int64 tracking_time
uint32 type

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['id','position','velocity','heading','bounding_box','tracking_time','type']
  _slot_types = ['int32','geometry_msgs/Vector3','geometry_msgs/Vector3','float64','geometry_msgs/Vector3','int64','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,position,velocity,heading,bounding_box,tracking_time,type

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PerceptionObject, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.position is None:
        self.position = geometry_msgs.msg.Vector3()
      if self.velocity is None:
        self.velocity = geometry_msgs.msg.Vector3()
      if self.heading is None:
        self.heading = 0.
      if self.bounding_box is None:
        self.bounding_box = geometry_msgs.msg.Vector3()
      if self.tracking_time is None:
        self.tracking_time = 0
      if self.type is None:
        self.type = 0
    else:
      self.id = 0
      self.position = geometry_msgs.msg.Vector3()
      self.velocity = geometry_msgs.msg.Vector3()
      self.heading = 0.
      self.bounding_box = geometry_msgs.msg.Vector3()
      self.tracking_time = 0
      self.type = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_i10dqI().pack(_x.id, _x.position.x, _x.position.y, _x.position.z, _x.velocity.x, _x.velocity.y, _x.velocity.z, _x.heading, _x.bounding_box.x, _x.bounding_box.y, _x.bounding_box.z, _x.tracking_time, _x.type))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.Vector3()
      if self.velocity is None:
        self.velocity = geometry_msgs.msg.Vector3()
      if self.bounding_box is None:
        self.bounding_box = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 96
      (_x.id, _x.position.x, _x.position.y, _x.position.z, _x.velocity.x, _x.velocity.y, _x.velocity.z, _x.heading, _x.bounding_box.x, _x.bounding_box.y, _x.bounding_box.z, _x.tracking_time, _x.type,) = _get_struct_i10dqI().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_i10dqI().pack(_x.id, _x.position.x, _x.position.y, _x.position.z, _x.velocity.x, _x.velocity.y, _x.velocity.z, _x.heading, _x.bounding_box.x, _x.bounding_box.y, _x.bounding_box.z, _x.tracking_time, _x.type))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.Vector3()
      if self.velocity is None:
        self.velocity = geometry_msgs.msg.Vector3()
      if self.bounding_box is None:
        self.bounding_box = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 96
      (_x.id, _x.position.x, _x.position.y, _x.position.z, _x.velocity.x, _x.velocity.y, _x.velocity.z, _x.heading, _x.bounding_box.x, _x.bounding_box.y, _x.bounding_box.z, _x.tracking_time, _x.type,) = _get_struct_i10dqI().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i10dqI = None
def _get_struct_i10dqI():
    global _struct_i10dqI
    if _struct_i10dqI is None:
        _struct_i10dqI = struct.Struct("<i10dqI")
    return _struct_i10dqI
